#!/bin/bash

# Configuration
PROJECT_ID="bankisha-654d0"
REGION="asia-northeast1"
IMAGE_NAME="gcr.io/$PROJECT_ID/bankisha-app"

# Firebase Public Variables (Expected to be set in environment)
FIREBASE_API_KEY="${FIREBASE_API_KEY:-}"
FIREBASE_AUTH_DOMAIN="${FIREBASE_AUTH_DOMAIN:-}"
FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID:-$PROJECT_ID}"
FIREBASE_STORAGE_BUCKET="${FIREBASE_STORAGE_BUCKET:-}"
FIREBASE_MESSAGING_SENDER_ID="${FIREBASE_MESSAGING_SENDER_ID:-}"
FIREBASE_APP_ID="${FIREBASE_APP_ID:-}"
FIREBASE_FUNCTIONS_URL="${FIREBASE_FUNCTIONS_URL:-}"

# Gemini API Key (Must be set via environment)
GEMINI_API_KEY="${GEMINI_API_KEY:-}"

# Firebase Admin Credentials (Runtime)
FIREBASE_CLIENT_EMAIL="${FIREBASE_CLIENT_EMAIL:-}"
FIREBASE_PRIVATE_KEY="${FIREBASE_PRIVATE_KEY:-}"

echo "🚀 Starting deployment for $PROJECT_ID..."

# Build and Push using Cloud Build
gcloud builds submit --config cloudbuild.yaml \
  --substitutions=_IMAGE_NAME=$IMAGE_NAME,\
_FIREBASE_API_KEY=$FIREBASE_API_KEY,\
_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN,\
_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID,\
_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET,\
_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID,\
_FIREBASE_APP_ID=$FIREBASE_APP_ID,\
_FIREBASE_FUNCTIONS_URL=$FIREBASE_FUNCTIONS_URL

# Deploy to Cloud Run
gcloud run deploy bankisha-app \
  --image $IMAGE_NAME \
  --region $REGION \
  --platform managed \
  --allow-unauthenticated \
  --set-env-vars GEMINI_API_KEY=$GEMINI_API_KEY,FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL,FIREBASE_PRIVATE_KEY="$FIREBASE_PRIVATE_KEY",FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID

echo "✅ Deployment complete!"
